import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "AnimeList",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <link href="https://cdn.lineicons.com/5.0/lineicons.css" rel="stylesheet" />
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="w-full flex flex-row items-center justify-between border px-20 py-3 ">
          <h1 className="font-bold text-md md:text-2xl">ANIMELIST</h1>
          <div className="relative">
            <input className="focus:decoration-0 border rounded-xl px-2 py-1 w-full" type="text" placeholder="Search..."></input>
            <button className="absolute right-5 top-1 text-xl">
              <i class="lni lni-search-1 "></i>
            </button>
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
